global using MatchingEngine.Models;
global using MatchingEngine.Data;
global using MatchingEngine.Services;
global using MatchingEngine.Hubs;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.AspNetCore.SignalR;
global using Microsoft.AspNetCore.Mvc;
